#!/usr/bin/env python3
"""
Fast Sync Deployer for Campus Job Posting System
Uploads modified and missing production files to /htdocs/ on InfinityFree.
"""

import os
import sys
import time
from ftplib import FTP, error_perm

HOST = 'ftpupload.net'
USER = 'if0_43050820'
PASS = 'Alwinson100'

EXCLUDE_DIRS = {
    'node_modules',
    '.git',
    '.github',
    '.agents',
    '.codex',
    '.superpowers',
    '.scratch',
    'scratch',
    'playwright-report',
    'test-results',
    'screenshots',
    'tests',
    'tools',
    'qa'
}

EXCLUDE_FILES = {
    'test_dump.sql',
    'package-lock.json',
    'bun.lock',
    'playwright.config.ts',
    '.env',
    '.env.production',
    'cute_robot.original.glb.bak',
    'dbtest.php'
}

def should_exclude(rel_path, is_dir=False):
    parts = rel_path.replace('\\', '/').strip('/').split('/')
    for part in parts:
        if part in EXCLUDE_DIRS:
            return True
        if part.startswith('.') and part not in ('.htaccess',):
            return True
    filename = parts[-1]
    if not is_dir:
        if filename in EXCLUDE_FILES or filename.endswith('.bak') or filename.endswith('.tmp'):
            return True
    return False

def collect_files(base_dir):
    file_list = []
    for root, dirs, files in os.walk(base_dir):
        dirs[:] = [d for d in dirs if not should_exclude(os.path.relpath(os.path.join(root, d), base_dir), is_dir=True)]
        for file in files:
            full_path = os.path.join(root, file)
            rel = os.path.relpath(full_path, base_dir)
            if not should_exclude(rel, is_dir=False):
                file_list.append((full_path, rel.replace('\\', '/')))
    return file_list

def get_ftp():
    ftp = FTP(HOST, timeout=30)
    ftp.login(USER, PASS)
    ftp.set_pasv(True)
    return ftp

def ensure_dir(ftp, remote_dir, created_dirs):
    if remote_dir in created_dirs:
        return
    dirs = [d for d in remote_dir.strip('/').split('/') if d]
    current = ''
    for d in dirs:
        current += '/' + d
        if current in created_dirs:
            continue
        try:
            ftp.cwd(current)
            created_dirs.add(current)
        except error_perm:
            try:
                ftp.mkd(current)
                ftp.cwd(current)
                created_dirs.add(current)
            except error_perm:
                pass

def main():
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    print(f"Connecting to {HOST} as {USER}...")
    ftp = get_ftp()
    print("Connected.")

    all_files = collect_files(base_dir)
    print(f"Auditing {len(all_files)} production candidate files against /htdocs/...")

    to_upload = []
    for full_path, rel_path in all_files:
        # Don't upload proof uploads generated by test suites
        if rel_path.startswith('uploads/proofs/'):
            continue
        remote_path = f"/htdocs/{rel_path}"
        local_size = os.path.getsize(full_path)
        try:
            remote_size = ftp.size(remote_path)
            if remote_size != local_size:
                to_upload.append((full_path, rel_path, local_size, f"diff ({local_size} vs {remote_size})"))
        except Exception:
            to_upload.append((full_path, rel_path, local_size, "missing"))

    print(f"\nFound {len(to_upload)} files needing upload.")
    if not to_upload:
        print("Everything is up to date!")
        ftp.quit()
        return

    created_dirs = set()
    current_dir = None
    start_time = time.time()
    total_bytes = sum(item[2] for item in to_upload)
    uploaded_bytes = 0

    print(f"Starting upload of {len(to_upload)} files ({total_bytes / 1024 / 1024:.2f} MB)...\n")

    for idx, (local_path, rel_path, size, reason) in enumerate(to_upload, 1):
        remote_rel_dir = os.path.dirname(rel_path).replace('\\', '/')
        target_dir = f"/htdocs/{remote_rel_dir}".rstrip('/')
        filename = os.path.basename(rel_path)

        ensure_dir(ftp, target_dir, created_dirs)
        if current_dir != target_dir:
            ftp.cwd(target_dir)
            current_dir = target_dir

        size_str = f"{size/1024:.1f} KB" if size < 1024*1024 else f"{size/1024/1024:.2f} MB"
        print(f"[{idx}/{len(to_upload)}] Uploading ({reason}): /{rel_path} ({size_str})...")

        for attempt in range(1, 4):
            try:
                with open(local_path, 'rb') as fp:
                    ftp.storbinary(f'STOR {filename}', fp, blocksize=262144)
                uploaded_bytes += size
                break
            except Exception as e:
                print(f"  [RETRY {attempt}/3] {e}")
                time.sleep(1.5)
                try: ftp.quit()
                except: pass
                ftp = get_ftp()
                current_dir = None
                ensure_dir(ftp, target_dir, created_dirs)
                ftp.cwd(target_dir)
                current_dir = target_dir

    # Finalize .env
    prod_env = os.path.join(base_dir, '.env.production')
    if os.path.exists(prod_env):
        print("\nVerifying /htdocs/.env credentials...")
        try:
            ftp.cwd('/htdocs')
            with open(prod_env, 'rb') as fp:
                ftp.storbinary('STOR .env', fp)
            print("  • /htdocs/.env finalized.")
        except Exception as e:
            print(f"  [WARN] Failed to finalize .env: {e}")

    try:
        ftp.quit()
    except Exception:
        pass

    duration = time.time() - start_time
    print(f"\n[SUCCESS] Sync complete! Uploaded {len(to_upload)} files ({uploaded_bytes/1024/1024:.2f} MB) in {duration:.1f}s.")
    print("Live Website: http://tgm.freehosting.dev/")

if __name__ == '__main__':
    main()
